### Basic Options ###

# The directory to store the downloaded file
dir=${ARIA2_DOWNLOAD_DIR}

# Downloads the URIs listed in FILE
input-file=.\aria2.session

# The file name of the log file
log=.\aria2.log

# Set the maximum number of parallel downloads for every queue item
# Default: 5
max-concurrent-downloads=5

# Check file integrity by validating piece hashes or a hash of entire file
# Default: false
check-integrity=false

# Continue downloading a partially downloaded file
continue=true

### HTTP/FTP/SFTP Options ###

# The maximum number of connections to one server for each download
# Default: 1
max-connection-per-server=1

# Aria2 does not split less than 2*SIZE byte range
# Default: 20M
min-split-size=20M

# Download a file using N connections
# Default: 5
split=5

### RPC Options ###

# Enable JSON-RPC/XML-RPC server
# Default: false
enable-rpc=false

# Pause download after added
# Default: false
pause=false

# Add Access-Control-Allow-Origin header field with value * to the RPC response
# Default: false
rpc-allow-origin-all=false

# Use the certificate in FILE for RPC server. The certificate must be either in PKCS12 (.p12, .pfx) or in PEM format
rpc-certificate=

# Listen incoming JSON-RPC/XML-RPC requests on all network interfaces
# Default: false
rpc-listen-all=false

# Specify a port number for JSON-RPC/XML-RPC server to listen to
# Default: 6800
rpc-listen-port=6800

# Use the private key in FILE for RPC server
rpc-private-key=

# Set RPC secret authorization token
rpc-secret=

# RPC transport will be encrypted by SSL/TLS
rpc-secure=false

### Advanced Options ###

# Restart download from scratch if the corresponding control file doesn't exist
# Default: false
allow-overwrite=false

# If false is given, aria2 aborts download when a piece length is different from one in a control file
# Default: false
allow-piece-length-change=false

# Always resume download
# Default: true
always-resume=true

# Enable asynchronous DNS
# Default: true
async-dns=true

# Rename file name if the same file already exists
# Default: true
auto-file-renaming=true

# Handle quoted string in Content-Disposition header as UTF-8 instead of ISO-8859-1
# Default: false
content-disposition-default-utf8=false

# Enable disk cache
# Default: 16M
disk-cache=16M

# Specify file allocation method
# Default: prealloc
file-allocation=prealloc

# Set log level to output
# Default: debug
log-level=debug

# Set max overall download speed in bytes/sec
# Default: 0
max-overall-download-limit=0

# Set max download speed per each download in bytes/sec
# Default: 0
max-download-limit=0

# No file allocation is made for files whose size is smaller than SIZE
# Default: 5M
no-file-allocation-limit=5M

# Make aria2 quiet (no console output)
# Default: false
quiet=false

# Save error/unfinished downloads to FILE on exit
save-session=.\aria2.session

# Save error/unfinished downloads to a file specified by --save-session option every SEC seconds
# Default: 0
save-session-interval=0
